# This file contains pre-commit hooks for checking the C++ code. Since these
# hooks require tools that may not be trivial to install (unlike the Python
# hooks like flake8), we keep these in a separate file to be applied manually.
repos:
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: python
    hooks:
      - id: clang-format
        # Unclear if this is necessary, it seems like clang-format uses
        # .clang-format if found by default, at least for newer versions. I'll
        # specify this here just in case.
        args:
        - --style=file
        exclude: 'extern/.*'
      - id: clang-tidy
        # Ignore external files and those taken verbatim from HOOMD.
        exclude: 'AABB\.h|extern.*'
        args: [--warnings-as-errors=*]
# Set up the cppcheck hook manually, the one provided by the above repo is configured too rigidly.
-   repo: local
    hooks:
      - id: cppcheck
        # Ignore external files and those taken verbatim from HOOMD.
        name: cppcheck
        entry: cppcheck
        language: system
        files: '.*\.(h|cc)'
        exclude: '.*AABB\.h|extern.*'
        args:
        - cpp/
        - --enable=warning,style,performance,portability # Ignore unused (could be used by Cython).
        - --std=c++14
        - --language=c++ # Force C++ for .h header files.
        - --inline-suppr # Enable inline suppresions of warnings.
        - -icpp/locality/AABBTree.cc
        - --suppress=*:cpp/locality/AABB.h
        - --suppress=*:extern/*
        - --error-exitcode=1
