version: 2

references:
  container: &test_container_config
    docker:
      - image: vramasub/freud:20180122
    working_directory: ~/ci/freud

  load_code: &load_code
    checkout

  get_requirements: &get_requirements
    run:
      name: install dependencies
      command: |
        pip install --user -r requirements.txt
        pip3 install --user -r requirements.txt

  configure: &configure
    run:
      name: Configure
      command: |
        mkdir build
        cd build
        echo pyver=${PYVER}
        cmake ../ -DPYTHON_EXECUTABLE=/usr/bin/python${PYVER}

  compile: &compile
    run:
      name: Compile
      working_directory: build
      command: |
        make -j4
        make install

  test: &test
    run:
      name: run tests
      command: ${NOSE}

  store: &store
    store_artifacts:
      path: test-reports
      destination: test-reports

  build_and_test: &build_and_test
    steps:
      - *load_code
      - *get_requirements
      - *configure
        #- *save_requirements
      - *compile
      - *test
      - *store

jobs:
  test-py27:
    <<: *test_container_config
    environment:
      PYVER: "2.7"
      NOSE: "nosetests"
    <<: *build_and_test

  test-py34:
    <<: *test_container_config
    environment:
      PYVER: "3.4"
      NOSE: "python3.4 -m nose"
    <<: *build_and_test

  test-py35:
    <<: *test_container_config
    environment:
      PYVER: "3.5"
      NOSE: "python3.5 -m nose"
    <<: *build_and_test

  test-py36:
    <<: *test_container_config
    environment:
      PYVER: "3.6"
      NOSE: "python3.6 -m nose"
    <<: *build_and_test

workflows:
  version: 2
  all:
    jobs:
      - test-py27:
      - test-py34:
      - test-py35:
      - test-py36:
