version: 2

references:
  container_ubuntu: &test_container_config_ubuntu
    docker:
      - image: vramasub/freud_py35_ubuntu:20180124
    working_directory: ~/ci/freud

  container_arch: &test_container_config_arch
    docker:
      - image: vramasub/freud_py36_arch:20180124
    working_directory: ~/ci/freud

  load_code: &load_code
    checkout

  get_requirements_ubuntu: &get_requirements_ubuntu
    run:
      name: Install dependencies
      command: |
        pip install --user -r requirements.txt
        pip3 install --user -r requirements.txt

  get_requirements_arch: &get_requirements_arch
    run:
      name: Install dependencies
      command: |
        pip install --user -r requirements.txt

  configure: &configure
    run:
      name: Configure
      command: |
        if [ -d build ]; then
            rm -rf build
        fi
        rm freud/_freud.cpp
        mkdir build
        cd build
        echo pyver=${PYVER}
        cmake ../ -DPYTHON_EXECUTABLE=/usr/bin/python${PYVER} -DENABLE_CYTHON=ON

  compile: &compile
    run:
      name: Compile
      working_directory: build
      command: |
        make -j4
        make install

  test_ubuntu: &test_ubuntu
    run:
      name: Run unit tests
      command: |
          cd ~
          python -m unittest discover ~/ci/freud/tests/ -v

  test_arch: &test_arch
    run:
      name: Run unit tests
      command: |
          cd ~
          python -m unittest discover ~/ci/freud/tests/ -v

  store: &store
    store_artifacts:
      path: test-reports
      destination: test-reports

  build_and_test_ubuntu: &build_and_test_ubuntu
    steps:
      - *load_code
      - *get_requirements_ubuntu
      - *configure
      - *compile
      - *test_ubuntu
      - *store

  build_and_test_arch: &build_and_test_arch
    steps:
      - *load_code
      - *get_requirements_arch
      - *configure
      - *compile
      - *test_arch
      - *store

jobs:
  test-py27:
    <<: *test_container_config_ubuntu
    environment:
      PYVER: "2.7"
    <<: *build_and_test_ubuntu

  test-py35:
    <<: *test_container_config_ubuntu
    environment:
      PYVER: "3.5"
    <<: *build_and_test_ubuntu

  test-py36:
    <<: *test_container_config_arch
    environment:
      PYVER: "3.6"
    <<: *build_and_test_arch

workflows:
  version: 2
  all:
    jobs:
      - test-py27
      - test-py35
      - test-py36
