version: 2

references:
  container_ubuntu: &test_container_config_ubuntu
    docker:
      - image: vramasub/freud_py35_ubuntu:20180723
    working_directory: ~/ci/freud

  container_arch: &test_container_config_arch
    docker:
      - image: vramasub/freud_py36_arch:20180124
    working_directory: ~/ci/freud

  load_code: &load_code
    checkout

  get_requirements: &get_requirements
    run:
      name: Install dependencies
      command: |
        git submodule update --init
        pip${PYVER} install --user -r requirements.txt
        pip${PYVER} install --user flake8
        pip${PYVER} install --user coverage

  check_source: &check_source
    run:
      name: flake8
      command: |
        python${PYVER} -m flake8 --show-source .

  build: &build
    run:
      name: Build
      command: |
        echo "PYVER=${PYVER}"
        python${PYVER} setup.py build_ext --inplace --coverage

  test: &test
    run:
      name: Run unit tests
      command: |
          export PATH=~/.local/bin:${PATH}
          coverage run -m unittest discover tests -v
          export CODECOV_TOKEN=4ce7f171-1f0a-4cc9-a6c3-594a7af1987c
          bash <(curl -s https://codecov.io/bash)


  store: &store
    store_artifacts:
      path: test-reports
      destination: test-reports

  build_and_test: &build_and_test
    steps:
      - *load_code
      - *get_requirements
      - *check_source
      - *build
      - *test
      - *store

jobs:
  test-py27:
    <<: *test_container_config_ubuntu
    environment:
      PYVER: "2.7"
    <<: *build_and_test

  test-py35:
    <<: *test_container_config_ubuntu
    environment:
      PYVER: "3.5"
    <<: *build_and_test

  test-py36:
    <<: *test_container_config_arch
    environment:
      PYVER: "3.6"
    <<: *build_and_test

workflows:
  version: 2
  all:
    jobs:
      - test-py27
      - test-py35
      - test-py36
