version: 2

references:
  container_ubuntu: &test_container_config_ubuntu
    docker:
      - image: vramasub/freud_py35_ubuntu:20180629
    working_directory: ~/ci/freud

  container_arch: &test_container_config_arch
    docker:
      - image: vramasub/freud_py36_arch:20180124
    working_directory: ~/ci/freud

  load_code: &load_code
    checkout

  get_requirements: &get_requirements
    run:
      name: Install dependencies
      command: |
        pip${PYVER} install --user -r requirements.txt

  configure: &configure
    run:
      name: Configure
      command: |
        if [ -d build ]; then
            rm -rf build
        fi
        if [ -f freud/_freud.cpp ]; then
            rm freud/_freud.cpp
        fi
        mkdir build
        cd build
        echo "PYVER=${PYVER}"
        cmake ../ -DPYTHON_EXECUTABLE=/usr/bin/python${PYVER} -DENABLE_CYTHON=ON

  compile: &compile
    run:
      name: Compile
      working_directory: build
      command: |
        make -j4
        make install

  test: &test
    run:
      name: Run unit tests
      command: |
          cd ~
          python${PYVER} -m unittest discover ~/ci/freud/tests/ -v

  store: &store
    store_artifacts:
      path: test-reports
      destination: test-reports

  build_and_test: &build_and_test
    steps:
      - *load_code
      - *get_requirements
      - *configure
      - *compile
      - *test
      - *store

jobs:
  test-py27:
    <<: *test_container_config_ubuntu
    environment:
      PYVER: "2.7"
    <<: *build_and_test

  test-py35:
    <<: *test_container_config_ubuntu
    environment:
      PYVER: "3.5"
    <<: *build_and_test

  test-py36:
    <<: *test_container_config_arch
    environment:
      PYVER: "3.6"
    <<: *build_and_test

workflows:
  version: 2
  all:
    jobs:
      - test-py27
      - test-py35
      - test-py36
